branches:
  only:
    - master

language: python
notifications:
  email: false
python:
  - "2.7"
  - "3.5"
before_install :
  - sudo apt-get install -qq libboost-dev
install:
  - python setup.py bdist_wheel
  - pip install --pre --no-index --find-links dist/ ad3

script: true
