branches:
  only:
    - master

notifications:
  email: false

language: python

matrix:
    include:
        - os: linux
          sudo: false
          python: 2.7
        - os: linux
          sudo: false
          python: 3.5
        - os: osx
          language: generic

install:
  - pip install nosetests
  - python setup.py bdist_wheel
  - pip install --pre --no-index --find-links dist/ ad3

script:
  - mkdir empty_folder; cd empty_folder; nosetests -vs ad3
